-- test-run result file version 2
test_run = require('test_run').new()
 | ---
 | ...

--
-- gh-3228: Check the error message in the case of a __serialize
-- function generating infinite recursion.
--
setmetatable({}, {__serialize = function(a) return a end})
 | ---
 | - error: 'console: an exception occurred when formatting the output: Bad __serialize
 |     function. It can''t return the same value.'
 | ...

--
--Check that __eq metamethod is ignored.
--
local table = setmetatable({}, {__eq = function(a, b) return a ~= b end})
 | ---
 | ...
setmetatable(table, {__serialize = function(a) return a end})
 | ---
 | - error: 'console: an exception occurred when formatting the output: Bad __serialize
 |     function. It can''t return the same value.'
 | ...
